using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Generates a city-like road layout using a 2D L-system and spawns
/// procedural buildings along the roads.
/// 
/// This script is self-contained and does not rely on the tutorial
/// helper scripts. It uses a discrete grid for road cells and instantiates
/// road and building prefabs based on that layout.
/// </summary>
public class LSystemRoadCityGenerator : MonoBehaviour
{
    // ----------------------------
    // L-System Configuration
    // ----------------------------

    [Header("L-System Road Grammar")]
    [Tooltip("Starting string for the road L-system.")]
    public string axiom = "F";

    [Tooltip("Number of expansion iterations for the road grammar.")]
    public int iterations = 3;

    [System.Serializable]
    public struct RoadRule
    {
        public char predecessor;
        public string successor;
    }

    [Tooltip("Production rules for the road L-system.")]
    public RoadRule[] rules;

    [Tooltip("Maximum number of neighbouring road cells allowed for a building to spawn here (to avoid busy intersections).")]
    [Range(1, 4)]
    public int maxNeighboursForBuilding = 2;

    // ----------------------------
    // Grid / Turtle Configuration
    // ----------------------------

    [Header("Grid Settings")]
    [Tooltip("World-space size of one grid cell (both X and Z).")]
    public float cellSize = 4f;

    [Tooltip("Starting grid position (in world space, rounded to nearest cell).")]
    public Vector3 startPosition = Vector3.zero;

    public enum Dir { Up, Right, Down, Left }

    [Header("Turtle Settings")]
    [Tooltip("Initial facing direction for the turtle.")]
    public Dir initialDirection = Dir.Up;

    // ----------------------------
    // Road & Building Prefabs
    // ----------------------------

    [Header("Prefabs")]

    [Tooltip("Road segment prefab; a simple quad/cube is fine.")]
    public GameObject roadPrefab;

    [Tooltip("Prefab that contains a ProceduralBuildingGenerator component.")]
    public ProceduralBuildingGenerator buildingGeneratorPrefab;

    [Tooltip("Optional variety: different grammars for buildings.")]
    public GrammarAsset[] buildingGrammars;

    [Tooltip("Optional variety: different visual themes for buildings.")]
    public BuildingTheme[] buildingThemes;

    [Header("Building Placement")]
    [Tooltip("Distance, in grid cells, from road to building.")]
    public int buildingOffsetCells = 2;

    [Range(0f, 1f)]
    [Tooltip("Probability to spawn a building at a given road cell.")]
    public float buildingSpawnProbability = 0.3f;

    [Header("Road Shape")]
    [Tooltip("How many grid cells each 'F' should advance the turtle.")]
    public int forwardStepCells = 3;

    // ----------------------------
    // Internal State
    // ----------------------------

    private HashSet<Vector2Int> roadCells = new HashSet<Vector2Int>();
    private List<GameObject> spawnedRoads = new List<GameObject>();
    private List<GameObject> spawnedBuildings = new List<GameObject>();

    // ----------------------------
    // Public Entry Points
    // ----------------------------

    /// <summary>
    /// Generates a new road layout and spawns buildings.
    /// </summary>
    [ContextMenu("Generate L-System City")]
    public void GenerateCity()
    {
        if (roadPrefab == null)
        {
            Debug.LogError("LSystemRoadCityGenerator: No roadPrefab assigned.");
            return;
        }

        if (buildingGeneratorPrefab == null)
        {
            Debug.LogWarning("LSystemRoadCityGenerator: No buildingGeneratorPrefab assigned. Roads only will be generated.");
        }

        ClearCity();

        string sentence = ExpandLSystem();
        BuildRoadCellsFromSentence(sentence);
        InstantiateRoads();
        InstantiateBuildingsAlongRoads();

        Debug.Log($"[LSystemRoadCityGenerator] City generated. RoadCells: {roadCells.Count}, Roads: {spawnedRoads.Count}, Buildings: {spawnedBuildings.Count}");
    }

    /// <summary>
    /// Clears all roads and buildings previously generated by this script.
    /// </summary>
    [ContextMenu("Clear City")]
    public void ClearCity()
    {
        foreach (var r in spawnedRoads)
        {
            if (r != null)
                DestroyImmediateOrRuntime(r);
        }
        spawnedRoads.Clear();

        foreach (var b in spawnedBuildings)
        {
            if (b != null)
                DestroyImmediateOrRuntime(b);
        }
        spawnedBuildings.Clear();

        roadCells.Clear();
    }

    // ----------------------------
    // L-System Expansion
    // ----------------------------

    private string ExpandLSystem()
    {
        string current = axiom;

        // Build dictionary for faster lookup
        Dictionary<char, string> ruleDict = new Dictionary<char, string>();
        foreach (var r in rules)
        {
            if (!ruleDict.ContainsKey(r.predecessor))
                ruleDict.Add(r.predecessor, r.successor);
        }

        for (int i = 0; i < iterations; i++)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            foreach (char c in current)
            {
                if (ruleDict.TryGetValue(c, out string successor))
                    sb.Append(successor);
                else
                    sb.Append(c);
            }
            current = sb.ToString();
        }

        return current;
    }

    // ----------------------------
    // Turtle Interpretation
    // ----------------------------

    private void BuildRoadCellsFromSentence(string sentence)
    {
        roadCells.Clear();

        Vector3 worldStart = startPosition;
        worldStart.x = Mathf.Round(worldStart.x / cellSize) * cellSize;
        worldStart.z = Mathf.Round(worldStart.z / cellSize) * cellSize;

        Vector2Int pos = WorldToGrid(worldStart);
        Dir dir = initialDirection;
        Stack<(Vector2Int, Dir)> stack = new Stack<(Vector2Int, Dir)>();

        roadCells.Add(pos);

        foreach (char c in sentence)
        {
            switch (c)
            {
                case 'F':
                    for (int i = 0; i < forwardStepCells; i++)
                    {
                        pos += DirToVector(dir);
                        roadCells.Add(pos);
                    }
                    break;

                case '+':
                    dir = TurnRight(dir);
                    break;

                case '-':
                    dir = TurnLeft(dir);
                    break;

                case '[':
                    stack.Push((pos, dir));
                    break;

                case ']':
                    if (stack.Count > 0)
                    {
                        var st = stack.Pop();
                        pos = st.Item1;
                        dir = st.Item2;
                    }
                    break;

                default:
                    break;
            }
        }
    }

    private Vector2Int WorldToGrid(Vector3 worldPos)
    {
        int gx = Mathf.RoundToInt(worldPos.x / cellSize);
        int gz = Mathf.RoundToInt(worldPos.z / cellSize);
        return new Vector2Int(gx, gz);
    }

    private Vector3 GridToWorld(Vector2Int gridPos)
    {
        return new Vector3(gridPos.x * cellSize, 0f, gridPos.y * cellSize);
    }

    private Vector2Int DirToVector(Dir dir)
    {
        switch (dir)
        {
            case Dir.Up:    return Vector2Int.up;
            case Dir.Right: return Vector2Int.right;
            case Dir.Down:  return Vector2Int.down;
            case Dir.Left:  return Vector2Int.left;
        }
        return Vector2Int.up;
    }

    private Dir TurnRight(Dir dir)
    {
        return (Dir)(((int)dir + 1) % 4);
    }

    private Dir TurnLeft(Dir dir)
    {
        return (Dir)(((int)dir + 3) % 4); // +3 mod 4 is -1
    }

    // ----------------------------
    // Instantiation: Roads
    // ----------------------------

    private void InstantiateRoads()
    {
        foreach (var cell in roadCells)
        {
            Vector3 worldPos = GridToWorld(cell) + transform.position;

            GameObject road = Instantiate(roadPrefab, worldPos, Quaternion.identity, transform);

            // Scale the road tile to fill one grid cell
            Vector3 scale = road.transform.localScale;
            scale.x = cellSize;
            scale.z = cellSize;
            road.transform.localScale = scale;

            spawnedRoads.Add(road);
        }
    }

    // ----------------------------
    // Instantiation: Buildings
    // ----------------------------

    private void InstantiateBuildingsAlongRoads()
    {
        if (buildingGeneratorPrefab == null)
            return;

        HashSet<Vector2Int> occupied = new HashSet<Vector2Int>(roadCells);

        foreach (var cell in roadCells)
        {
            // count neighbours
            bool hasUp    = roadCells.Contains(cell + Vector2Int.up);
            bool hasDown  = roadCells.Contains(cell + Vector2Int.down);
            bool hasLeft  = roadCells.Contains(cell + Vector2Int.left);
            bool hasRight = roadCells.Contains(cell + Vector2Int.right);

            int neighbourCount =
                (hasUp ? 1 : 0) +
                (hasDown ? 1 : 0) +
                (hasLeft ? 1 : 0) +
                (hasRight ? 1 : 0);

            // avoid chaotic intersections
            if (neighbourCount == 0 || neighbourCount > maxNeighboursForBuilding)
                continue;

            List<Vector2Int> possibleSides = new List<Vector2Int>();

            if (hasUp || hasDown)
            {
                possibleSides.Add(Vector2Int.left);
                possibleSides.Add(Vector2Int.right);
            }
            if (hasLeft || hasRight)
            {
                possibleSides.Add(Vector2Int.up);
                possibleSides.Add(Vector2Int.down);
            }

            if (possibleSides.Count == 0)
                continue;

            if (Random.value > buildingSpawnProbability)
                continue;

            Vector2Int sideDir = possibleSides[Random.Range(0, possibleSides.Count)];
            Vector2Int buildingCell = cell + sideDir * buildingOffsetCells;

            if (occupied.Contains(buildingCell))
                continue;

            occupied.Add(buildingCell);

            Vector3 worldPos = GridToWorld(buildingCell) + transform.position;
            Vector3 forward = -new Vector3(sideDir.x, 0f, sideDir.y);
            if (forward.sqrMagnitude < 0.001f)
                forward = Vector3.forward;

            Quaternion rot = Quaternion.LookRotation(forward, Vector3.up);

            ProceduralBuildingGenerator building =
                Instantiate(buildingGeneratorPrefab, worldPos, rot, transform);

            if (buildingGrammars != null && buildingGrammars.Length > 0)
            {
                int gi = Random.Range(0, buildingGrammars.Length);
                building.grammarAsset = buildingGrammars[gi];
            }

            if (buildingThemes != null && buildingThemes.Length > 0)
            {
                int ti = Random.Range(0, buildingThemes.Length);
                building.ApplyTheme(buildingThemes[ti]);
            }

            if (building.grammarAsset != null)
            {
                building.grammarAsset.randomSeed = -1;
            }

            building.Generate();
            spawnedBuildings.Add(building.gameObject);
        }
    }


    // ----------------------------
    // Utility
    // ----------------------------

    private void DestroyImmediateOrRuntime(GameObject go)
    {
        if (go == null) return;

#if UNITY_EDITOR
        if (!Application.isPlaying)
            Object.DestroyImmediate(go);
        else
            Object.Destroy(go);
#else
        Object.Destroy(go);
#endif
    }

    private void OnDrawGizmosSelected()
    {
        // Just draw the start position as a small cube.
        Gizmos.color = Color.yellow;
        Gizmos.DrawCube(startPosition, Vector3.one);
    }
}
